spring:
  application:
     name: banking
  datasource:
    url: jdbc:h2:file:./bank_DB
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
springdoc:
  api-docs:
    path: /api-docs